// Portland/Vancouver WA market rate catalog (2026)
// Typical Clark County / Portland metro handyman rates — final pricing after scope review
// audience: "homeowner" | "pm" — quote builder filters by role toggle

window.CATEGORY_ORDER_HOMEOWNER = [
  "general_handyman",
  "plumbing",
  "electrical",
  "carpentry",
  "drywall_surfaces",
  "painting",
  "windows_doors",
  "flooring",
  "kitchen",
  "bathroom",
  "appliance",
  "outdoor_exterior",
  "lighting_fixtures",
  "security_smart",
  "cleaning_maintenance",
  "assembly_install",
  "concrete_masonry",
  "garage_storage",
  "hvac_light",
  "specialty_misc",
];

window.CATEGORY_ORDER_PM = [
  "pm_turnover",
  "pm_inspection",
  "pm_maintenance",
  "pm_capex",
  "pm_preventative",
  "pm_move_io",
  "pm_exterior_common",
  "pm_emergency",
  "pm_standardization",
  "pm_specialty",
];

window.CATEGORY_LABELS = {
  general_handyman: "🔧 General Handyman",
  plumbing: "🚰 Plumbing",
  electrical: "⚡ Electrical",
  carpentry: "🧱 Carpentry & Woodwork",
  drywall_surfaces: "🧱 Drywall & Surfaces",
  painting: "🎨 Painting & Finishes",
  windows_doors: "🪟 Windows & Doors",
  flooring: "🏠 Flooring",
  kitchen: "🍽️ Kitchen",
  bathroom: "🚿 Bathroom",
  appliance: "🧰 Appliances",
  outdoor_exterior: "🌳 Outdoor & Exterior",
  lighting_fixtures: "💡 Lighting & Fixtures",
  security_smart: "🔐 Security & Smart Home",
  cleaning_maintenance: "🧹 Cleaning & Maintenance",
  assembly_install: "🪵 Assembly & Installation",
  concrete_masonry: "🧱 Concrete & Masonry",
  garage_storage: "🚪 Garage & Storage",
  hvac_light: "🌡️ HVAC Light Work",
  specialty_misc: "🐕 Specialty / Misc",
  pm_turnover: "🔄 Turnover / Unit Prep",
  pm_inspection: "🧾 Inspection & Compliance",
  pm_maintenance: "🔧 Maintenance Calls",
  pm_capex: "🏚️ CapEx / Rehab",
  pm_preventative: "🧰 Preventative Programs",
  pm_move_io: "🔐 Move-In / Move-Out",
  pm_exterior_common: "🚪 Exterior & Common Area",
  pm_emergency: "🧯 Emergency / After-Hours",
  pm_standardization: "🧱 Unit Standardization",
  pm_specialty: "🧼 Specialty PM Add-Ons",
};

window.REPAIR_CATALOG = [
  // ========== HOMEOWNER: GENERAL HANDYMAN ==========
  { id: "hm-general-repairs", audience: "homeowner", category: "general_handyman", name: "General repairs (handyman visit)", desc: "Trip charge plus typical small fixes in one visit — hinges, squeaks, loose hardware, minor adjustments.", low: 125, high: 275, unit: "first hour" },
  { id: "hm-home-maint", audience: "homeowner", category: "general_handyman", name: "Home maintenance visit", desc: "Seasonal check — filter reminders, caulking inspection, tightening fixtures, minor exterior spot-check.", low: 175, high: 350, unit: "per visit" },
  { id: "hm-punch-half", audience: "homeowner", category: "general_handyman", name: "Punch list completion", desc: "Multi-item punch list from inspection or closing — billed as blocked half-day.", low: 350, high: 650, unit: "up to 4 hr" },
  { id: "hm-odd-jobs", audience: "homeowner", category: "general_handyman", name: "Odd jobs / miscellaneous fixes", desc: "Catch-all small tasks — hooks, shelving tweaks, picture hanging prep, silicone touch-ups.", low: 95, high: 225, unit: "per hour" },
  { id: "hm-preventative", audience: "homeowner", category: "general_handyman", name: "Preventative maintenance package", desc: "Scheduled checklist — toilets, caulking, gutters spot-check, exterior penetrations caulk.", low: 225, high: 450, unit: "per visit" },

  // ========== HOMEOWNER: PLUMBING ==========
  { id: "plumb-faucet-bath", audience: "homeowner", category: "plumbing", name: "Faucet installation / repair (bath)", desc: "Replace or repair bathroom faucet; customer-supplied fixture.", low: 175, high: 325, unit: "per faucet" },
  { id: "plumb-faucet-kitchen", audience: "homeowner", category: "plumbing", name: "Faucet installation / repair (kitchen)", desc: "Kitchen faucet swap including sprayer lines.", low: 200, high: 375, unit: "per faucet" },
  { id: "plumb-toilet", audience: "homeowner", category: "plumbing", name: "Toilet installation / replacement", desc: "Remove and install toilet with wax ring and supply.", low: 275, high: 475, unit: "per toilet" },
  { id: "plumb-toilet-unclog", audience: "homeowner", category: "plumbing", name: "Toilet unclogging", desc: "Clear toilet clog with auger; excludes main line blockage.", low: 125, high: 275, unit: "per toilet" },
  { id: "plumb-toilet-internals", audience: "homeowner", category: "plumbing", name: "Toilet repair (running / weak flush)", desc: "Flapper, fill valve, flush lever replacement.", low: 100, high: 175, unit: "per toilet" },
  { id: "plumb-sink-install", audience: "homeowner", category: "plumbing", name: "Sink installation / replacement", desc: "Drop-in or vanity sink hookup using existing supplies.", low: 225, high: 450, unit: "per sink" },
  { id: "plumb-disposal", audience: "homeowner", category: "plumbing", name: "Garbage disposal install / repair", desc: "Swap disposal or clear jam & reset; wiring within handyman scope.", low: 175, high: 350, unit: "per unit" },
  { id: "plumb-leak", audience: "homeowner", category: "plumbing", name: "Leak detection & repair (fixture)", desc: "Under-sink, toilet, or exposed pipe leak repair.", low: 125, high: 325, unit: "per repair" },
  { id: "plumb-drain", audience: "homeowner", category: "plumbing", name: "Drain cleaning / unclogging", desc: "Kitchen or lav drain snake; not main sewer.", low: 150, high: 325, unit: "per fixture" },
  { id: "plumb-water-line", audience: "homeowner", category: "plumbing", name: "Water line hookup (ice maker / fridge)", desc: "Stub-out to appliance valve using flexible supply.", low: 125, high: 275, unit: "per line" },
  { id: "plumb-wh-tank", audience: "homeowner", category: "plumbing", name: "Water heater swap assist", desc: "Like-for-like tank disconnect/reconnect after plumber delivery — coordination variant.", low: 275, high: 550, unit: "per heater" },
  { id: "plumb-wh-tankless", audience: "homeowner", category: "plumbing", name: "Tankless water heater — trim-out help", desc: "Mounting assistance & trim within non-licensed scope; licensed plumber for gas/flue as required.", low: 350, high: 750, unit: "assist only" },
  { id: "plumb-sump", audience: "homeowner", category: "plumbing", name: "Sump pump installation / replacement", desc: "Replace pump in existing pit with check valve.", low: 275, high: 550, unit: "per pump" },
  { id: "plumb-pipe-repair", audience: "homeowner", category: "plumbing", name: "Exposed pipe repair", desc: "Small copper/PVC repairs in accessible areas.", low: 175, high: 400, unit: "per repair" },
  { id: "plumb-repipe-note", audience: "homeowner", category: "plumbing", name: "Partial repiping (quote)", desc: "Galvanized/PVC upgrades — scoped after walkthrough.", low: 650, high: 2500, unit: "project" },
  { id: "plumb-gas-note", audience: "homeowner", category: "plumbing", name: "Gas line work", desc: "Licensed plumber required for many gas tasks — we coordinate or scope minor appliance pulls.", low: 200, high: 500, unit: "consult" },
  { id: "plumb-supply", audience: "homeowner", category: "plumbing", name: "Supply line replacement", desc: "Braided supplies under sink or toilet.", low: 75, high: 150, unit: "per line" },
  { id: "plumb-shower-head", audience: "homeowner", category: "plumbing", name: "Shower trim / showerhead swap", desc: "Replace trim kit or showerhead; customer-supplied.", low: 100, high: 225, unit: "per shower" },
  { id: "plumb-caulk-bath", audience: "homeowner", category: "plumbing", name: "Re-caulk tub/shower", desc: "Strip failed caulk, mildew-resistant silicone.", low: 150, high: 275, unit: "per bath" },
  { id: "plumb-caulk-kitchen", audience: "homeowner", category: "plumbing", name: "Re-caulk kitchen sink / backsplash", desc: "Fresh silicone at sink and counter seams.", low: 100, high: 200, unit: "per kitchen" },

  // ========== HOMEOWNER: ELECTRICAL ==========
  { id: "elec-light", audience: "homeowner", category: "electrical", name: "Light fixture installation", desc: "Swap fixture on existing box.", low: 125, high: 225, unit: "per fixture" },
  { id: "elec-outlet-cover", audience: "homeowner", category: "electrical", name: "Outlet / switch cover plates", desc: "Replace cracked or mismatched plates; up to ~20 devices.", low: 75, high: 150, unit: "batch" },
  { id: "elec-outlet-switch", audience: "homeowner", category: "electrical", name: "Outlet / switch replacement", desc: "Like-for-like swap on existing wiring.", low: 95, high: 175, unit: "per device" },
  { id: "elec-ceiling-fan", audience: "homeowner", category: "electrical", name: "Ceiling fan install / replace", desc: "Fan-rated box required.", low: 200, high: 375, unit: "per fan" },
  { id: "elec-thermostat-smart", audience: "homeowner", category: "electrical", name: "Smart thermostat installation", desc: "Replace stat with smart unit; common wire check.", low: 150, high: 275, unit: "per stat" },
  { id: "elec-security-light", audience: "homeowner", category: "electrical", name: "Security / motion lighting", desc: "Mount flood or motion fixture at existing circuit.", low: 175, high: 350, unit: "per fixture" },
  { id: "elec-wiring-repair", audience: "homeowner", category: "electrical", name: "Minor wiring repairs", desc: "Loose pigtails, pigtail fixes in accessible boxes.", low: 125, high: 275, unit: "per hour" },
  { id: "elec-troubleshoot", audience: "homeowner", category: "electrical", name: "Electrical troubleshooting visit", desc: "Investigate tripping breaker or dead outlet — simple faults.", low: 175, high: 350, unit: "per visit" },
  { id: "elec-gfci", audience: "homeowner", category: "electrical", name: "GFCI outlet installation", desc: "Replace receptacle with GFCI.", low: 100, high: 175, unit: "per outlet" },
  { id: "elec-dimmer", audience: "homeowner", category: "electrical", name: "Dimmer switch installation", desc: "Customer-supplied dimmer.", low: 90, high: 160, unit: "per switch" },
  { id: "elec-doorbell", audience: "homeowner", category: "electrical", name: "Doorbell / video doorbell install", desc: "Replace chime or smart doorbell.", low: 125, high: 250, unit: "per unit" },
  { id: "elec-bath-fan", audience: "homeowner", category: "electrical", name: "Bathroom exhaust fan replacement", desc: "Existing duct and wiring.", low: 200, high: 375, unit: "per fan" },
  { id: "elec-camera-lowvolt", audience: "homeowner", category: "electrical", name: "Camera mount & power setup", desc: "Customer-supplied Wi‑Fi cam — mounting & outlet/USB power routing.", low: 125, high: 275, unit: "per camera" },

  // ========== HOMEOWNER: CARPENTRY ==========
  { id: "car-trim", audience: "homeowner", category: "carpentry", name: "Trim / molding installation", desc: "Door/window casing or base shoe.", low: 200, high: 450, unit: "per room" },
  { id: "car-base-crown", audience: "homeowner", category: "carpentry", name: "Baseboards / crown molding", desc: "Install pre-primed trim; paint optional.", low: 275, high: 650, unit: "per room" },
  { id: "car-door-install", audience: "homeowner", category: "carpentry", name: "Interior door install / repair", desc: "Prehung or slab hang & hardware.", low: 200, high: 425, unit: "per door" },
  { id: "car-door-lock", audience: "homeowner", category: "carpentry", name: "Door lock installation", desc: "Deadbolt or knob set.", low: 100, high: 175, unit: "per lock" },
  { id: "car-cabinet-install", audience: "homeowner", category: "carpentry", name: "Cabinet installation", desc: "Wall/base cabinets — customer-supplied.", low: 450, high: 1200, unit: "per run" },
  { id: "car-shelving", audience: "homeowner", category: "carpentry", name: "Shelving / storage builds", desc: "Floating shelves or closet shelving.", low: 175, high: 450, unit: "project" },
  { id: "car-custom", audience: "homeowner", category: "carpentry", name: "Custom carpentry (quoted)", desc: "Built-ins, mantels, benches — scoped.", low: 500, high: 3500, unit: "project" },
  { id: "car-closet-org", audience: "homeowner", category: "carpentry", name: "Closet organizer installation", desc: "Wire or laminate system from retailer kit.", low: 225, high: 550, unit: "per closet" },
  { id: "car-handrail", audience: "homeowner", category: "carpentry", name: "Handrail install / repair", desc: "Interior stair handrail secure or replace on existing stairs.", low: 175, high: 400, unit: "per run" },

  // ========== HOMEOWNER: DRYWALL & SURFACES ==========
  { id: "dw-install-small", audience: "homeowner", category: "drywall_surfaces", name: "Drywall patch / small install", desc: "Small sections or patches under 4 sq ft.", low: 175, high: 350, unit: "per area" },
  { id: "dw-small-patch", audience: "homeowner", category: "drywall_surfaces", name: "Small drywall patch", desc: "Nail holes & dings up to ~2\".", low: 75, high: 125, unit: "per area" },
  { id: "dw-med-patch", audience: "homeowner", category: "drywall_surfaces", name: "Medium drywall patch", desc: "Holes ~2–6\".", low: 150, high: 275, unit: "per patch" },
  { id: "dw-large-patch", audience: "homeowner", category: "drywall_surfaces", name: "Large drywall patch", desc: "Holes 6\"+ with backer.", low: 275, high: 550, unit: "per patch" },
  { id: "dw-corner-bead", audience: "homeowner", category: "drywall_surfaces", name: "Corner bead repair", desc: "Metal/vinyl corner repair.", low: 150, high: 300, unit: "per corner" },
  { id: "dw-texture", audience: "homeowner", category: "drywall_surfaces", name: "Texture matching", desc: "Orange peel/knockdown blend after patch.", low: 125, high: 275, unit: "per patch" },
  { id: "dw-ceiling", audience: "homeowner", category: "drywall_surfaces", name: "Ceiling repair", desc: "Water stain cut-out & patch or nail-pop fix.", low: 225, high: 550, unit: "per area" },
  { id: "dw-water-damage", audience: "homeowner", category: "drywall_surfaces", name: "Water damage drywall repair", desc: "Dry-out coordination + patch/paint-ready.", low: 350, high: 900, unit: "per room" },

  // ========== HOMEOWNER: PAINTING ==========
  { id: "paint-touchup", audience: "homeowner", category: "painting", name: "Interior paint touch-ups", desc: "Match & blend small areas.", low: 120, high: 220, unit: "per visit" },
  { id: "paint-room", audience: "homeowner", category: "painting", name: "Interior — single room (walls)", desc: "Prep, cut-in, two coats; customer paint.", low: 350, high: 650, unit: "per room" },
  { id: "paint-room-trim", audience: "homeowner", category: "painting", name: "Interior — room walls + trim", desc: "Walls, base, casing; customer paint.", low: 600, high: 1100, unit: "per room" },
  { id: "paint-exterior-touch", audience: "homeowner", category: "painting", name: "Exterior painting (localized)", desc: "Trim, shutters, or single elevation touch.", low: 450, high: 1200, unit: "project" },
  { id: "paint-exterior-full", audience: "homeowner", category: "painting", name: "Exterior repaint (quoted)", desc: "Whole-home exterior — subcontract coordination.", low: 4500, high: 14000, unit: "home" },
  { id: "paint-whole-interior", audience: "homeowner", category: "painting", name: "Whole-home interior painting", desc: "Typical ~1500–2500 sqft living.", low: 3500, high: 8500, unit: "home" },
  { id: "paint-feature", audience: "homeowner", category: "painting", name: "Feature / accent wall", desc: "Single wall emphasis.", low: 175, high: 400, unit: "per wall" },
  { id: "paint-fence", audience: "homeowner", category: "painting", name: "Fence stain / paint", desc: "Prep & coat wood fence.", low: 350, high: 1200, unit: "project" },
  { id: "paint-cabinets", audience: "homeowner", category: "painting", name: "Cabinet painting / refinishing", desc: "Spray or brush cabinet faces.", low: 1800, high: 4500, unit: "kitchen" },
  { id: "paint-faux", audience: "homeowner", category: "painting", name: "Decorative / faux finish", desc: "Accent techniques.", low: 350, high: 900, unit: "per area" },

  // ========== HOMEOWNER: WINDOWS & DOORS ==========
  { id: "wd-window-replace", audience: "homeowner", category: "windows_doors", name: "Window replacement assist", desc: "Install prepared RO insert windows — scoped.", low: 275, high: 550, unit: "per opening" },
  { id: "wd-window-seal", audience: "homeowner", category: "windows_doors", name: "Window sealing / weatherstrip", desc: "Foam, seals, sash adjustments.", low: 125, high: 275, unit: "per window" },
  { id: "wd-treatments", audience: "homeowner", category: "windows_doors", name: "Window treatments install", desc: "Blinds, brackets, rods.", low: 95, high: 225, unit: "per window" },
  { id: "door-interior-replace", audience: "homeowner", category: "windows_doors", name: "Interior door replacement", desc: "Customer-supplied prehung.", low: 200, high: 425, unit: "per door" },
  { id: "door-ext-note", audience: "homeowner", category: "windows_doors", name: "Exterior door replacement", desc: "Often multi-trade — scoped install.", low: 450, high: 1200, unit: "per door" },
  { id: "door-sliding", audience: "homeowner", category: "windows_doors", name: "Sliding door repair", desc: "Track clean, rollers, lock adjustment.", low: 150, high: 375, unit: "per door" },
  { id: "door-rekey", audience: "homeowner", category: "windows_doors", name: "Rekey locks", desc: "Single door cylinder rekey.", low: 75, high: 125, unit: "per door" },
  { id: "door-deadbolt", audience: "homeowner", category: "windows_doors", name: "Deadbolt installation", desc: "New bore or swap.", low: 100, high: 175, unit: "per lock" },
  { id: "door-knob", audience: "homeowner", category: "windows_doors", name: "Door knob / lever replacement", desc: "Standard bore.", low: 75, high: 140, unit: "per door" },
  { id: "door-smart-lock", audience: "homeowner", category: "windows_doors", name: "Smart lock installation", desc: "Programming assist.", low: 150, high: 275, unit: "per lock" },
  { id: "door-adjust", audience: "homeowner", category: "windows_doors", name: "Door adjust / plane / shim", desc: "Sticking or latch misalignment.", low: 100, high: 200, unit: "per door" },
  { id: "door-hinge", audience: "homeowner", category: "windows_doors", name: "Hinge replacement", desc: "Customer hinges.", low: 75, high: 150, unit: "per door" },
  { id: "door-frame-strike", audience: "homeowner", category: "windows_doors", name: "Jamb / strike repair", desc: "Security plate or split jamb repair.", low: 175, high: 400, unit: "per door" },
  { id: "door-cabinet-hw", audience: "homeowner", category: "windows_doors", name: "Cabinet hardware swap", desc: "Pulls/knobs up to ~25 pcs.", low: 150, high: 325, unit: "kitchen" },
  { id: "wd-weatherstrip", audience: "homeowner", category: "windows_doors", name: "Weather stripping upgrade", desc: "Door sweeps & perimeter seals.", low: 125, high: 275, unit: "per door" },

  // ========== HOMEOWNER: FLOORING ==========
  { id: "fl-hardwood", audience: "homeowner", category: "flooring", name: "Hardwood repair / patch", desc: "Board replacement small areas.", low: 275, high: 650, unit: "project" },
  { id: "fl-laminate", audience: "homeowner", category: "flooring", name: "Laminate / vinyl plank install", desc: "Floating LVP in box rooms.", low: 2.5, high: 5.5, unit: "per sq ft" },
  { id: "fl-tile", audience: "homeowner", category: "flooring", name: "Tile install / repair", desc: "Backsplash or bath floor patches.", low: 450, high: 1200, unit: "project" },
  { id: "fl-carpet-patch", audience: "homeowner", category: "flooring", name: "Carpet patch / transition", desc: "Small patch or reducer strip.", low: 125, high: 325, unit: "per area" },
  { id: "fl-refinish-note", audience: "homeowner", category: "flooring", name: "Floor refinishing", desc: "Partner sand & finish quote.", low: 3.5, high: 7, unit: "per sq ft" },
  { id: "fl-epoxy-garage", audience: "homeowner", category: "flooring", name: "Garage epoxy coating", desc: "Decorative flake system — scoped.", low: 1200, high: 3500, unit: "2-car" },

  // ========== HOMEOWNER: KITCHEN ==========
  { id: "kit-remodel-partial", audience: "homeowner", category: "kitchen", name: "Kitchen refresh (partial)", desc: "Counters, backsplash, fixtures coordination.", low: 2500, high: 12000, unit: "project" },
  { id: "kit-counter", audience: "homeowner", category: "kitchen", name: "Countertop installation assist", desc: "Removal/prep for slab install coordination.", low: 400, high: 1200, unit: "project" },
  { id: "kit-sink", audience: "homeowner", category: "kitchen", name: "Kitchen sink replacement", desc: "Includes faucet reconnect.", low: 275, high: 525, unit: "per sink" },
  { id: "kit-appliance", audience: "homeowner", category: "kitchen", name: "Built-in appliance install", desc: "Dishwasher, range, OTR micro — haul-away extra.", low: 175, high: 375, unit: "per appliance" },
  { id: "kit-cabinets", audience: "homeowner", category: "kitchen", name: "Cabinet boxes install", desc: "IKEA/big-box assembly & hang.", low: 450, high: 1200, unit: "project" },
  { id: "kit-backsplash", audience: "homeowner", category: "kitchen", name: "Backsplash tile", desc: "Ceramic subway typical.", low: 800, high: 2200, unit: "kitchen" },

  // ========== HOMEOWNER: BATHROOM ==========
  { id: "bath-remodel", audience: "homeowner", category: "bathroom", name: "Bathroom remodel (quoted)", desc: "Vanity, toilet, fixtures swap mid-scope.", low: 4500, high: 22000, unit: "project" },
  { id: "bath-shower", audience: "homeowner", category: "bathroom", name: "Shower door / surround repair", desc: "Seal, hardware, minor leaks.", low: 175, high: 450, unit: "per shower" },
  { id: "bath-tub", audience: "homeowner", category: "bathroom", name: "Bathtub replacement assist", desc: "Surround demo coordination.", low: 800, high: 2500, unit: "project" },
  { id: "bath-vanity", audience: "homeowner", category: "bathroom", name: "Vanity installation", desc: "Freestanding or floating.", low: 275, high: 550, unit: "per vanity" },
  { id: "bath-tile-grout", audience: "homeowner", category: "bathroom", name: "Tile / grout repair", desc: "Regrout corners & cracked grout.", low: 225, high: 550, unit: "per bath" },
  { id: "bath-grab-bar", audience: "homeowner", category: "bathroom", name: "Grab bar installation", desc: "Studs or anchors in wet area; customer-supplied bar.", low: 100, high: 200, unit: "per bar" },

  // ========== HOMEOWNER: APPLIANCES ==========
  { id: "app-install", audience: "homeowner", category: "appliance", name: "Appliance installation", desc: "Washer/dryer, fridge water.", low: 125, high: 275, unit: "per unit" },
  { id: "app-replace", audience: "homeowner", category: "appliance", name: "Appliance swap-out", desc: "Disconnect/connect like-for-like.", low: 95, high: 200, unit: "per unit" },
  { id: "app-repair-note", audience: "homeowner", category: "appliance", name: "Minor appliance repair assist", desc: "Cord, leveling, trim kits — not sealed-system.", low: 95, high: 225, unit: "per visit" },
  { id: "app-gas-hook", audience: "homeowner", category: "appliance", name: "Gas appliance hookup", desc: "Licensed plumber where required.", low: 175, high: 400, unit: "per appliance" },

  // ========== HOMEOWNER: OUTDOOR & EXTERIOR ==========
  { id: "ext-fence-install", audience: "homeowner", category: "outdoor_exterior", name: "Fence installation / sections", desc: "Wood panels — scoped.", low: 750, high: 4500, unit: "project" },
  { id: "ext-fence-gate", audience: "homeowner", category: "outdoor_exterior", name: "Fence gate repair", desc: "Rehang, hinges, latch.", low: 175, high: 375, unit: "per gate" },
  { id: "ext-fence-board", audience: "homeowner", category: "outdoor_exterior", name: "Fence board replacement", desc: "Up to ~6 pickets.", low: 150, high: 325, unit: "visit" },
  { id: "ext-deck-repair", audience: "homeowner", category: "outdoor_exterior", name: "Deck repair / boards", desc: "Localized rot replacement.", low: 350, high: 1200, unit: "project" },
  { id: "ext-deck-build-note", audience: "homeowner", category: "outdoor_exterior", name: "Deck construction", desc: "Permitted decks — partner GC.", low: 8000, high: 35000, unit: "project" },
  { id: "ext-patio", audience: "homeowner", category: "outdoor_exterior", name: "Patio / landing repair", desc: "Concrete pad minor repairs.", low: 275, high: 850, unit: "project" },
  { id: "ext-pressure-wash", audience: "homeowner", category: "outdoor_exterior", name: "Pressure washing", desc: "House/drive/walk.", low: 250, high: 550, unit: "visit" },
  { id: "ext-gutter-clean", audience: "homeowner", category: "outdoor_exterior", name: "Gutter cleaning", desc: "Single-story typical.", low: 175, high: 325, unit: "home" },
  { id: "ext-gutter-repair", audience: "homeowner", category: "outdoor_exterior", name: "Gutter repair / downspouts", desc: "Rehang, seal corners.", low: 125, high: 325, unit: "per run" },
  { id: "ext-siding-patch", audience: "homeowner", category: "outdoor_exterior", name: "Siding patch repair", desc: "Vinyl/Hardie localized.", low: 275, high: 750, unit: "area" },
  { id: "ext-roof-minor", audience: "homeowner", category: "outdoor_exterior", name: "Roof minor repair", desc: "Pipe boot, couple shingles — weather permitting.", low: 225, high: 550, unit: "repair" },
  { id: "ext-trim-paint", audience: "homeowner", category: "outdoor_exterior", name: "Exterior trim touch-up paint", desc: "Localized sanding/prime/paint.", low: 200, high: 425, unit: "visit" },
  { id: "ext-caulk", audience: "homeowner", category: "outdoor_exterior", name: "Exterior caulk & seal", desc: "Penetrations & window perimeters.", low: 175, high: 350, unit: "visit" },
  { id: "ext-screen", audience: "homeowner", category: "outdoor_exterior", name: "Window screen repair", desc: "Rescreen frames.", low: 60, high: 130, unit: "per screen" },
  { id: "ext-house-numbers", audience: "homeowner", category: "outdoor_exterior", name: "House numbers / mailbox mount", desc: "Hardware install.", low: 90, high: 175, unit: "item" },

  // ========== HOMEOWNER: LIGHTING & FIXTURES ==========
  { id: "lit-interior-extra", audience: "homeowner", category: "lighting_fixtures", name: "Interior accent lighting", desc: "Picture lights, under-cab LED strips.", low: 125, high: 325, unit: "fixture" },
  { id: "lit-exterior", audience: "homeowner", category: "lighting_fixtures", name: "Exterior sconces / coach lights", desc: "Swap on existing boxes.", low: 125, high: 275, unit: "per fixture" },
  { id: "lit-landscape", audience: "homeowner", category: "lighting_fixtures", name: "Low-voltage landscape lighting", desc: "Path lights transformer tie-in.", low: 275, high: 850, unit: "project" },
  { id: "lit-holiday", audience: "homeowner", category: "lighting_fixtures", name: "Holiday lighting installation", desc: "Clip-style roof line — takedown optional.", low: 225, high: 650, unit: "home" },

  // ========== HOMEOWNER: SECURITY & SMART ==========
  { id: "sec-camera", audience: "homeowner", category: "security_smart", name: "Security camera installation", desc: "Mounts & routing for wired/Wi‑Fi cams.", low: 125, high: 325, unit: "per camera" },
  { id: "sec-smart-lock", audience: "homeowner", category: "security_smart", name: "Smart lock setup", desc: "Overlap with doors cat — keyed convenience.", low: 150, high: 275, unit: "per lock" },
  { id: "sec-doorbell", audience: "homeowner", category: "security_smart", name: "Video doorbell", desc: "Power kit install if needed.", low: 125, high: 250, unit: "each" },
  { id: "sec-motion-sensor", audience: "homeowner", category: "security_smart", name: "Motion sensor / smart sensor mount", desc: "Standalone IoT sensors.", low: 75, high: 175, unit: "each" },
  { id: "sec-smoke", audience: "homeowner", category: "security_smart", name: "Smoke / CO alarm install", desc: "Battery or retrofit wired.", low: 50, high: 110, unit: "each" },

  // ========== HOMEOWNER: CLEANING & MAINTENANCE ==========
  { id: "cl-deep", audience: "homeowner", category: "cleaning_maintenance", name: "Deep cleaning coordination", desc: "Partner cleaner referral & keys.", low: 225, high: 450, unit: "visit" },
  { id: "cl-move", audience: "homeowner", category: "cleaning_maintenance", name: "Move-out cleaning coordination", desc: "Whole-home turnover clean vendor.", low: 275, high: 550, unit: "home" },
  { id: "cl-junk", audience: "homeowner", category: "cleaning_maintenance", name: "Junk / debris hauling assist", desc: "Bag & curb load — disposal fees extra.", low: 175, high: 450, unit: "load" },
  { id: "cl-garage", audience: "homeowner", category: "cleaning_maintenance", name: "Garage cleanout / organize", desc: "Labor to sort & haul away coordination.", low: 275, high: 750, unit: "bay" },

  // ========== HOMEOWNER: ASSEMBLY & INSTALL ==========
  { id: "asm-furniture", audience: "homeowner", category: "assembly_install", name: "Furniture assembly", desc: "Flat-pack dresser, desk, IKEA.", low: 75, high: 225, unit: "piece" },
  { id: "asm-tv", audience: "homeowner", category: "assembly_install", name: "TV wall mounting", desc: "Bracket into studs; conceal trim optional.", low: 125, high: 275, unit: "tv" },
  { id: "asm-art", audience: "homeowner", category: "assembly_install", name: "Art / mirror hanging", desc: "Heavy mirror french cleat.", low: 95, high: 225, unit: "piece" },
  { id: "asm-blinds", audience: "homeowner", category: "assembly_install", name: "Curtain / blinds installation", desc: "Rods & brackets.", low: 95, high: 225, unit: "window" },
  { id: "asm-shelf", audience: "homeowner", category: "assembly_install", name: "Shelf installation", desc: "Floating / bracketed.", low: 95, high: 250, unit: "shelf" },

  // ========== HOMEOWNER: CONCRETE & MASONRY ==========
  { id: "cm-concrete-patch", audience: "homeowner", category: "concrete_masonry", name: "Concrete crack / patch repair", desc: "Epoxy or patching compound.", low: 175, high: 450, unit: "area" },
  { id: "cm-driveway-seal", audience: "homeowner", category: "concrete_masonry", name: "Driveway sealing", desc: "Asphalt or concrete sealer application.", low: 275, high: 750, unit: "driveway" },
  { id: "cm-slab-small", audience: "homeowner", category: "concrete_masonry", name: "Small slab pour / pads", desc: "AC pad / landing — partner pour.", low: 650, high: 2200, unit: "pad" },
  { id: "cm-steps", audience: "homeowner", category: "concrete_masonry", name: "Step / stoop repair", desc: "Tuck patch & tread fixes.", low: 275, high: 850, unit: "stairs" },

  // ========== HOMEOWNER: GARAGE & STORAGE ==========
  { id: "gs-opener", audience: "homeowner", category: "garage_storage", name: "Garage door opener install / repair", desc: "Motor swap or rail adjustment.", low: 275, high: 550, unit: "opener" },
  { id: "gs-racks", audience: "homeowner", category: "garage_storage", name: "Storage racks / overhead", desc: "Ceiling-mounted steel racks.", low: 175, high: 425, unit: "rack" },
  { id: "gs-shed", audience: "homeowner", category: "garage_storage", name: "Shed assembly", desc: "Prefab resin/metal kit.", low: 450, high: 1400, unit: "shed" },
  { id: "gs-workbench", audience: "homeowner", category: "garage_storage", name: "Workbench installation", desc: "Cabinet workbench bolt-up.", low: 175, high: 450, unit: "bench" },

  // ========== HOMEOWNER: HVAC LIGHT ==========
  { id: "hvac-stat", audience: "homeowner", category: "hvac_light", name: "Thermostat replacement", desc: "Battery or low-voltage stat swap.", low: 95, high: 185, unit: "each" },
  { id: "hvac-vent-clean", audience: "homeowner", category: "hvac_light", name: "Supply vent cleaning / vacuum", desc: "Registers & boots reachable.", low: 125, high: 275, unit: "home" },
  { id: "hvac-filter", audience: "homeowner", category: "hvac_light", name: "Filter replacement service", desc: "Sizing & replacement schedule sticker.", low: 75, high: 150, unit: "visit" },
  { id: "hvac-duct-tape", audience: "homeowner", category: "hvac_light", name: "Minor duct sealing / repair", desc: "Foil tape & saddle repairs accessible.", low: 125, high: 325, unit: "repair" },

  // ========== HOMEOWNER: SPECIALTY ==========
  { id: "sp-pet-door", audience: "homeowner", category: "specialty_misc", name: "Pet door installation", desc: "Door panel cut-in variant.", low: 225, high: 450, unit: "door" },
  { id: "sp-childproof", audience: "homeowner", category: "specialty_misc", name: "Childproofing package", desc: "Cabinet locks, anchors, gates.", low: 175, high: 425, unit: "home" },
  { id: "sp-soundproof", audience: "homeowner", category: "specialty_misc", name: "Soundproofing upgrades", desc: "Panels, seals, door sweep upgrades.", low: 350, high: 1200, unit: "room" },
  { id: "sp-holiday-decor", audience: "homeowner", category: "specialty_misc", name: "Holiday décor installation", desc: "Anchored exterior mounts.", low: 175, high: 450, unit: "visit" },
  { id: "sp-custom-odd", audience: "homeowner", category: "specialty_misc", name: "Custom odd builds", desc: "Quoted miscellaneous fabrication.", low: 250, high: 2500, unit: "project" },

  // ========== PROPERTY MANAGER: TURNOVER ==========
  { id: "pm-turn-full", audience: "pm", category: "pm_turnover", name: "Full unit turnover (rent-ready)", desc: "Paint touch/full walls, patch, fixtures, punch — scoped per sqft.", low: 1400, high: 4500, unit: "unit" },
  { id: "pm-turn-trash", audience: "pm", category: "pm_turnover", name: "Trash-out / junk removal", desc: "Left-behinds cleared; disposal billed.", low: 275, high: 900, unit: "unit" },
  { id: "pm-turn-deep-clean", audience: "pm", category: "pm_turnover", name: "Deep cleaning (turn)", desc: "Kitchen/bath/appliance deep clean coordination.", low: 225, high: 450, unit: "unit" },
  { id: "pm-turn-carpet-clean", audience: "pm", category: "pm_turnover", name: "Carpet cleaning / deodorize", desc: "Partner steam clean.", low: 125, high: 275, unit: "unit" },
  { id: "pm-turn-carpet-replace", audience: "pm", category: "pm_turnover", name: "Carpet replacement (rental grade)", desc: "Rip-out & pad — materials separate.", low: 650, high: 1800, unit: "unit" },
  { id: "pm-turn-repaint-full", audience: "pm", category: "pm_turnover", name: "Interior repaint — full unit", desc: "Neutral turnover palette.", low: 1600, high: 3800, unit: "unit" },
  { id: "pm-turn-repaint-touch", audience: "pm", category: "pm_turnover", name: "Interior repaint — touch-up", desc: "Walls only spot & blend.", low: 450, high: 1100, unit: "unit" },
  { id: "pm-turn-drywall", audience: "pm", category: "pm_turnover", name: "Drywall patch & repair (turn)", desc: "Typical nail holes + damages.", low: 275, high: 950, unit: "unit" },
  { id: "pm-turn-door-lock", audience: "pm", category: "pm_turnover", name: "Door / lock replacement & rekey", desc: "Keyed alike option.", low: 175, high: 450, unit: "unit" },
  { id: "pm-turn-blinds", audience: "pm", category: "pm_turnover", name: "Blinds / curtain replacement", desc: "Standard 2\" faux wood.", low: 225, high: 650, unit: "unit" },
  { id: "pm-turn-smoke-co", audience: "pm", category: "pm_turnover", name: "Smoke / CO detector replacement", desc: "Code-compliant locations.", low: 120, high: 280, unit: "unit" },
  { id: "pm-turn-led-bulbs", audience: "pm", category: "pm_turnover", name: "LED bulb full replacement", desc: "Uniform temps throughout.", low: 95, high: 225, unit: "unit" },
  { id: "pm-turn-plumb-minor", audience: "pm", category: "pm_turnover", name: "Minor plumbing (turn)", desc: "Leaks, flappers, aerators.", low: 175, high: 450, unit: "unit" },
  { id: "pm-turn-appliance-check", audience: "pm", category: "pm_turnover", name: "Appliance inspection / swap", desc: "Function check & like-for-like swap.", low: 125, high: 325, unit: "unit" },
  { id: "pm-turn-caulk", audience: "pm", category: "pm_turnover", name: "Caulking refresh (kitchen/bath)", desc: "Silicone at wet areas.", low: 150, high: 350, unit: "unit" },
  { id: "turn-walkthrough", audience: "pm", category: "pm_turnover", name: "Move-out walkthrough + scope", desc: "Photos & punch within 24 hr.", low: 125, high: 200, unit: "visit" },
  { id: "turn-mini", audience: "pm", category: "pm_turnover", name: "Mini turnover package", desc: "Up to ~4 hr punch.", low: 350, high: 525, unit: "unit" },
  { id: "turn-standard", audience: "pm", category: "pm_turnover", name: "Standard turnover — 1BR/studio", desc: "Patch, paint touch, caulk, hardware.", low: 750, high: 1400, unit: "unit" },
  { id: "turn-large", audience: "pm", category: "pm_turnover", name: "Standard turnover — 2BR+", desc: "Scaled for larger units.", low: 1100, high: 2200, unit: "unit" },
  { id: "turn-deep-clean-coord", audience: "pm", category: "pm_turnover", name: "Deep clean coordination", desc: "Vetted vendor scheduling.", low: 250, high: 500, unit: "unit" },

  // ========== PM: INSPECTION & COMPLIANCE ==========
  { id: "pm-insp-move", audience: "pm", category: "pm_inspection", name: "Move-in / move-out inspection", desc: "Photo documentation checklist.", low: 125, high: 225, unit: "unit" },
  { id: "pm-insp-section8", audience: "pm", category: "pm_inspection", name: "Section 8 / housing authority punch", desc: "Itemized fixes from failed inspection.", low: 225, high: 650, unit: "visit" },
  { id: "pm-insp-annual", audience: "pm", category: "pm_inspection", name: "Annual safety inspection", desc: "Walkthrough + summary.", low: 150, high: 275, unit: "unit" },
  { id: "pm-insp-smoke-co", audience: "pm", category: "pm_inspection", name: "Smoke / CO compliance check", desc: "Test, document, replace failed.", low: 95, high: 225, unit: "unit" },
  { id: "pm-insp-gfci", audience: "pm", category: "pm_inspection", name: "GFCI compliance upgrades", desc: "Per current code expectations.", low: 350, high: 900, unit: "unit" },
  { id: "pm-insp-handrail", audience: "pm", category: "pm_inspection", name: "Handrail / safety rail install", desc: "Interior/exterior grabs.", low: 225, high: 550, unit: "run" },
  { id: "pm-insp-trip", audience: "pm", category: "pm_inspection", name: "Trip hazard remediation", desc: "Transitions & thresholds.", low: 125, high: 350, unit: "item" },
  { id: "pm-insp-egress", audience: "pm", category: "pm_inspection", name: "Egress window readiness", desc: "Hardware/lubricate/adjust — not excavation.", low: 175, high: 450, unit: "opening" },
  { id: "pm-insp-wh-strap", audience: "pm", category: "pm_inspection", name: "Water heater strapping / seismic", desc: "Dual straps & flex connectors check.", low: 125, high: 275, unit: "heater" },
  { id: "pm-insp-dryer-vent", audience: "pm", category: "pm_inspection", name: "Dryer vent cleaning", desc: "Lint clear accessible runs.", low: 125, high: 275, unit: "unit" },

  // ========== PM: MAINTENANCE CALLS ==========
  { id: "pm-maint-leak", audience: "pm", category: "pm_maintenance", name: "Active leak service call", desc: "Isolate & temporary stop-gap if needed.", low: 175, high: 375, unit: "call" },
  { id: "pm-maint-toilet", audience: "pm", category: "pm_maintenance", name: "Toilet running / clogged", desc: "Auger internals as applicable.", low: 125, high: 275, unit: "call" },
  { id: "pm-maint-sink", audience: "pm", category: "pm_maintenance", name: "Sink / faucet issues", desc: "Tenant-report fixture fixes.", low: 125, high: 275, unit: "call" },
  { id: "pm-maint-disposal", audience: "pm", category: "pm_maintenance", name: "Garbage disposal jam / reset", desc: "Clear jam or quote replace.", low: 125, high: 225, unit: "call" },
  { id: "pm-maint-outlet", audience: "pm", category: "pm_maintenance", name: "Outlet not working", desc: "Reset GFCI branch troubleshoot.", low: 125, high: 275, unit: "call" },
  { id: "pm-maint-lights", audience: "pm", category: "pm_maintenance", name: "Flickering lights / ballast", desc: "Fixture & switch checks.", low: 125, high: 275, unit: "call" },
  { id: "pm-maint-door", audience: "pm", category: "pm_maintenance", name: "Door not closing / latching", desc: "Adjust striker/plane.", low: 95, high: 225, unit: "call" },
  { id: "pm-maint-window", audience: "pm", category: "pm_maintenance", name: "Window stuck / broken sash", desc: "Balance / lubricate / glaze spot.", low: 125, high: 325, unit: "opening" },
  { id: "pm-maint-hvac-light", audience: "pm", category: "pm_maintenance", name: "Minor HVAC — no heat / airflow", desc: "Filter, stat, power — not refrigerant.", low: 125, high: 275, unit: "call" },
  { id: "pm-maint-damage", audience: "pm", category: "pm_maintenance", name: "Tenant damage repair", desc: "Scoped patch & paint per incident.", low: 175, high: 650, unit: "ticket" },

  // ========== PM: CAPEX / REHAB ==========
  { id: "pm-cap-interior-full", audience: "pm", category: "pm_capex", name: "Full interior remodel (rent-ready)", desc: "Kitchen/bath/floor coordination.", low: 15000, high: 65000, unit: "unit" },
  { id: "pm-cap-kitchen", audience: "pm", category: "pm_capex", name: "Kitchen refresh", desc: "Cabinets, counters, paint.", low: 8000, high: 28000, unit: "kitchen" },
  { id: "pm-cap-bath", audience: "pm", category: "pm_capex", name: "Bathroom remodel", desc: "Fixture/surround upgrade.", low: 7000, high: 22000, unit: "bath" },
  { id: "pm-cap-lvp", audience: "pm", category: "pm_capex", name: "LVP flooring replacement", desc: "Whole-unit floating install.", low: 3.25, high: 6.5, unit: "per sq ft" },
  { id: "pm-cap-repaint", audience: "pm", category: "pm_capex", name: "Interior / exterior repaint", desc: "Portfolio repaint lanes.", low: 2200, high: 8500, unit: "unit" },
  { id: "pm-cap-windows", audience: "pm", category: "pm_capex", name: "Window replacement batch", desc: "Insert windows typical.", low: 450, high: 950, unit: "opening" },
  { id: "pm-cap-siding", audience: "pm", category: "pm_capex", name: "Siding repair / replacement", desc: "Localized or elevation.", low: 900, high: 8500, unit: "building" },
  { id: "pm-cap-roof", audience: "pm", category: "pm_capex", name: "Roof patch / minor replacement", desc: "Emergency tarp partner escalation.", low: 350, high: 1800, unit: "repair" },
  { id: "pm-cap-deck", audience: "pm", category: "pm_capex", name: "Deck rebuild / repair", desc: "Structural repairs scoped.", low: 1200, high: 12000, unit: "deck" },
  { id: "pm-cap-fence", audience: "pm", category: "pm_capex", name: "Fence replacement", desc: "Full sections.", low: 1500, high: 8500, unit: "job" },

  // ========== PM: PREVENTATIVE ==========
  { id: "pm-prev-quarterly", audience: "pm", category: "pm_preventative", name: "Quarterly inspection visits", desc: "Exterior/interior checklist.", low: 125, high: 225, unit: "visit" },
  { id: "pm-prev-filter", audience: "pm", category: "pm_preventative", name: "HVAC filter service plan", desc: "Scheduled replacements.", low: 65, high: 125, unit: "visit" },
  { id: "pm-prev-drain", audience: "pm", category: "pm_preventative", name: "Drain maintenance / enzyme treatment", desc: "Kitchen/lav preventative.", low: 95, high: 185, unit: "unit" },
  { id: "pm-prev-gutter", audience: "pm", category: "pm_preventative", name: "Gutter cleaning schedule", desc: "Bi-annual typical.", low: 175, high: 325, unit: "season" },
  { id: "pm-prev-roof-visual", audience: "pm", category: "pm_preventative", name: "Roof visual inspection", desc: "Photos & note deficiencies.", low: 125, high: 225, unit: "building" },
  { id: "pm-prev-exterior-walk", audience: "pm", category: "pm_preventative", name: "Exterior walk-through", desc: "Parking, siding, drainage.", low: 125, high: 225, unit: "site" },
  { id: "pm-prev-pest-seal", audience: "pm", category: "pm_preventative", name: "Pest prevention sealing", desc: "Foam/copper mesh entry points.", low: 175, high: 450, unit: "unit" },
  { id: "pm-prev-leak-check", audience: "pm", category: "pm_preventative", name: "Water leak early detection check", desc: "Angle stops, WH, lav traps.", low: 125, high: 225, unit: "unit" },
  { id: "pm-prev-seasonal", audience: "pm", category: "pm_preventative", name: "Seasonal maintenance", desc: "Winterization / summer prep checklist.", low: 175, high: 375, unit: "visit" },

  // ========== PM: MOVE IN / OUT ==========
  { id: "pm-mio-lock", audience: "pm", category: "pm_move_io", name: "Lock change / rekey", desc: "Master key systems welcome.", low: 95, high: 175, unit: "door" },
  { id: "pm-mio-welcome", audience: "pm", category: "pm_move_io", name: "Welcome repair checklist", desc: "Owner punch before tenant.", low: 225, high: 550, unit: "unit" },
  { id: "pm-mio-touch", audience: "pm", category: "pm_move_io", name: "Minor touch-ups before move-in", desc: "Paint/caulk/hardware.", low: 175, high: 425, unit: "unit" },
  { id: "pm-mio-assess", audience: "pm", category: "pm_move_io", name: "Move-out damage assessment", desc: "Photo evidence package.", low: 125, high: 225, unit: "unit" },
  { id: "pm-mio-deposit", audience: "pm", category: "pm_move_io", name: "Security deposit repair execution", desc: "Bid vs deposit cap coordination.", low: 275, high: 1800, unit: "list" },
  { id: "pm-mio-keys", audience: "pm", category: "pm_move_io", name: "Key duplication / lockbox setup", desc: "Vendor-neutral combo locks.", low: 75, high: 175, unit: "set" },

  // ========== PM: EXTERIOR & COMMON ==========
  { id: "pm-ext-stairs", audience: "pm", category: "pm_exterior_common", name: "Stair repair / handrails", desc: "Common-area metal/wood rails.", low: 275, high: 950, unit: "run" },
  { id: "pm-ext-striping", audience: "pm", category: "pm_exterior_common", name: "Parking striping touch-up", desc: "Localized repaint.", low: 350, high: 1200, unit: "lot" },
  { id: "pm-ext-pressure", audience: "pm", category: "pm_exterior_common", name: "Pressure washing (common)", desc: "Walkways & breezeways.", low: 275, high: 850, unit: "building" },
  { id: "pm-ext-trash-encl", audience: "pm", category: "pm_exterior_common", name: "Trash enclosure repair", desc: "Gates, hinges, hasps.", low: 225, high: 650, unit: "enclosure" },
  { id: "pm-ext-mailbox", audience: "pm", category: "pm_exterior_common", name: "Mailbox repair / replacement", desc: "Cluster boxes localized.", low: 125, high: 450, unit: "bank" },
  { id: "pm-ext-lighting", audience: "pm", category: "pm_exterior_common", name: "Exterior lighting maintenance", desc: "Bulbs, photocells, sconces.", low: 125, high: 325, unit: "visit" },
  { id: "pm-ext-fence-gate", audience: "pm", category: "pm_exterior_common", name: "Fence / gate repair", desc: "Perimeter repairs.", low: 175, high: 550, unit: "section" },
  { id: "pm-ext-landscape-light", audience: "pm", category: "pm_exterior_common", name: "Landscaping touch-ups (light)", desc: "Mulch edge, beds tidy — no maintenance contract.", low: 175, high: 450, unit: "visit" },

  // ========== PM: EMERGENCY ==========
  { id: "pm-em-water", audience: "pm", category: "pm_emergency", name: "Water leak / burst (after-hours)", desc: "Premium dispatch — isolate & temporize.", low: 275, high: 550, unit: "call" },
  { id: "pm-em-sewer", audience: "pm", category: "pm_emergency", name: "Sewer backup response", desc: "Coordinate snake/plumber — trip premium.", low: 325, high: 750, unit: "call" },
  { id: "pm-em-elec", audience: "pm", category: "pm_emergency", name: "Electrical failure / partial power", desc: "After-hours troubleshoot.", low: 275, high: 550, unit: "call" },
  { id: "pm-em-lockout", audience: "pm", category: "pm_emergency", name: "Lockout assistance", desc: "Rekey or drill cylinder PM-directed.", low: 175, high: 375, unit: "call" },
  { id: "pm-em-board", audience: "pm", category: "pm_emergency", name: "Board-up (break-in / glass)", desc: "Temporary plywood secure.", low: 275, high: 650, unit: "opening" },
  { id: "pm-em-storm", audience: "pm", category: "pm_emergency", name: "Storm damage temporary fixes", desc: "Tarps, fasteners.", low: 225, high: 550, unit: "call" },
  { id: "pm-em-heat", audience: "pm", category: "pm_emergency", name: "Heater failure (winter)", desc: "Stat/power/filters — escalate HVAC.", low: 225, high: 475, unit: "call" },

  // ========== PM: STANDARDIZATION ==========
  { id: "pm-std-fixtures", audience: "pm", category: "pm_standardization", name: "Standard fixture upgrade batch", desc: "Uniform faucets & lighting SKUs.", low: 225, high: 550, unit: "opening" },
  { id: "pm-std-appliance", audience: "pm", category: "pm_standardization", name: "Bulk appliance swaps", desc: "Portfolio replacements timeline.", low: 175, high: 325, unit: "unit" },
  { id: "pm-std-paint", audience: "pm", category: "pm_standardization", name: "Uniform paint conversion", desc: "Single company palette rollout.", low: 850, high: 2400, unit: "unit" },
  { id: "pm-std-lvp", audience: "pm", category: "pm_standardization", name: "Standard LVP across portfolio", desc: "Materials separate.", low: 2.75, high: 5.75, unit: "per sq ft" },
  { id: "pm-std-hardware", audience: "pm", category: "pm_standardization", name: "Hardware upgrades (handles/locks)", desc: "Keyed alike batches.", low: 450, high: 1400, unit: "unit" },

  // ========== PM: SPECIALTY ADD-ONS ==========
  { id: "pm-sp-odor", audience: "pm", category: "pm_specialty", name: "Odor removal (smoke / pets)", desc: "Partner ozone/fogging coordination.", low: 450, high: 1400, unit: "unit" },
  { id: "pm-sp-mold", audience: "pm", category: "pm_specialty", name: "Mold spot treatment (minor)", desc: "Surface remediation — not abatement.", low: 350, high: 950, unit: "area" },
  { id: "pm-sp-hoarder", audience: "pm", category: "pm_specialty", name: "Hoarder cleanouts", desc: "Labor + disposal coordination.", low: 750, high: 4500, unit: "unit" },
  { id: "pm-sp-bio", audience: "pm", category: "pm_specialty", name: "Biohazard light cleanup", desc: "Non-certified scope — referral if heavy.", low: 650, high: 2200, unit: "unit" },
  { id: "pm-sp-pest", audience: "pm", category: "pm_specialty", name: "Pest damage repair", desc: "After extermination drywall/finish.", low: 275, high: 1200, unit: "unit" },
  { id: "pm-sp-sound", audience: "pm", category: "pm_specialty", name: "Soundproofing between units", desc: "Panels, resilient channel patches.", low: 850, high: 4500, unit: "room" },
  { id: "pm-sp-camera", audience: "pm", category: "pm_specialty", name: "Security camera installation", desc: "Common-area mounts.", low: 175, high: 425, unit: "camera" },
];

// One-tap bundles (Uber-style bundles / Instacart “featured combos”) — adds multiple catalog line items
window.QUOTE_QUICK_STARTS = [
  {
    audience: "pm",
    bundleId: "pm-turnkey-1br",
    title: "Turnkey 1BR turnover",
    subtitle: "Walkthrough + standard turnover + deep clean coordination",
    badge: "Popular",
    addIds: ["turn-walkthrough", "turn-standard", "turn-deep-clean-coord"],
  },
  {
    audience: "pm",
    bundleId: "pm-move-in-ready",
    title: "Move-in essentials",
    subtitle: "Rekey + smoke/CO refresh + LED bulb swap",
    badge: null,
    addIds: ["pm-mio-lock", "pm-turn-smoke-co", "pm-turn-led-bulbs"],
  },
  {
    audience: "pm",
    bundleId: "pm-compliance-kit",
    title: "Compliance starter pass",
    subtitle: "Smoke/CO check + GFCI upgrades + dryer vent clean",
    badge: null,
    addIds: ["pm-insp-smoke-co", "pm-insp-gfci", "pm-insp-dryer-vent"],
  },
  {
    audience: "pm",
    bundleId: "pm-maintenance-trio",
    title: "Maintenance trio",
    subtitle: "Leak call + toilet + door latch tune-up templates",
    badge: null,
    addIds: ["pm-maint-leak", "pm-maint-toilet", "pm-maint-door"],
  },
  {
    audience: "homeowner",
    bundleId: "hm-half-day-punch",
    title: "Half-day punch list",
    subtitle: "Blocked multi-fix visit — ideal before listing or closing",
    badge: "Popular",
    addIds: ["hm-punch-half"],
  },
  {
    audience: "homeowner",
    bundleId: "hm-bath-refresh",
    title: "Bath refresh trio",
    subtitle: "Recaulk + faucet swap + toilet tune-up",
    badge: null,
    addIds: ["plumb-caulk-bath", "plumb-faucet-bath", "plumb-toilet-internals"],
  },
  {
    audience: "homeowner",
    bundleId: "hm-move-prep-clean",
    title: "Move prep basics",
    subtitle: "Deep clean coordination + junk hauling assist",
    badge: null,
    addIds: ["cl-move", "cl-junk"],
  },
];
